const patterns: [string, string][] = [
  ['?', 'd.sl'],
  ['Sunder', 'sunder'],
  ['?Bleed', 'leed.'],
  ['Ruthless Support', 'ruth'],
  ['Momentum Support', 'mome'],
  ['?Shield Charge', 'ld.ch'],
  ['Leap Slam', 'leap'],
  ['Faster Attacks Support', 'er.att'],
  ['?Sand Stance', 'sand'],
  ['Frostblink', 'stbl'],
  ['?Intimidating Cry', 'inti'],
  ['?Decoy Totem', 'ecoy'],
  ['?', 'ee.p'],
  ['Herald of Ash', 'of.as'],
  ['?', 'f.pu'],
  ['Blood Rage', 'od.r'],
  ['?Bombardment', 'omba'],
  ['Vulnerability', 'vuln'],
  ['?Automation', 'auto'],
  ['?', 'c.cr'],
  ['Pulverise Support', 'pulv'],
  ['?', 'fist.'],
  ['?', 'erex'],
];

const fps: Record<string, string> = {
  'Perforate': `Item Class: Skill Gems Rarity: Gem Perforate Attack, AoE, Slam, Melee Level: 1 Cost: 7 Mana Attack Speed: 80% of base Attack Damage: 218.5% of base Effectiveness of Added Damage: 218% Requirements: Level: 1 Smash the ground to bring forth multiple spears to damage enemies. When in Blood Stance, multiple spikes burst from the ground in sequence, able to hit enemies multiple times. In Sand Stance, the spikes are thrust outwards. Requires a Sword or Axe. You are in Blood Stance by default. Creates 7 Spikes 75% less Damage while in Blood Stance Experience: 1/70 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Steelskin': `Item Class: Skill Gems Rarity: Gem Steelskin Spell, Duration, Guard Level: 1 Cost: 4 Mana Cooldown Time: 3.00 sec Cast Time: Instant Requirements: Level: 4 Str: 16 Applies a buff which can take some of the damage from hits for you before being depleted. Shares a cooldown with other Guard skills. Base duration is 1.50 seconds This Skill's Cooldown does not recover during its effect 70% of Damage from Hits is taken from the Buff before Life or Energy Shield Buff can take 54 Damage Buff grants Immunity to Bleeding Experience: 1/841 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Crushing Fist': `Item Class: Skill Gems Rarity: Gem Crushing Fist Attack, Slam, AoE, Retaliation, Melee Level: 1 Cost: 8 Mana Cooldown Time: 4.00 sec Attack Speed: 70% of base Attack Damage: 1003.9% of base Effectiveness of Added Damage: 1003% Requirements: Level: 4 Str: 16 Retaliate against a blocked hit by calling forth a huge armoured fist to slam into the ground in front of you as you do the same, dealing weapon damage in an area. Cannot be used by default Becomes Usable once for 2 seconds when you Block a Hit Can't be Evaded 60% less Damage with Ailments Base radius is 2 metres Experience: 1/841 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Flesh and Stone': `Item Class: Skill Gems Rarity: Gem Flesh and Stone Spell, Aura, AoE, Stance, Physical Level: 1 Reservation: 25% Mana Cooldown Time: 2.00 sec Cast Time: Instant Requirements: Level: 16 Str: 26 Dex: 18 Buffs you, and affects nearby enemies with an aura, differently depending on your stance. Both stances are more impactful against enemies closer to you. Using the skill again alternates between Blood Stance and Sand Stance. Base Aura radius is 2.8 metres While in Blood Stance, Aura makes Enemies take up to 10% more Physical Damage from Hits While in Sand Stance, Buff makes you take up to 10% less Damage from Enemies in Aura Experience: 1/49,725 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Defiance Banner': `Item Class: Skill Gems Rarity: Gem Defiance Banner AoE, Spell, Duration, Aura Level: 1 Cost: 14 Mana Cooldown Time: 1.00 sec Cast Time: Instant Requirements: Level: 16 Str: 26 Dex: 18 You must gain Valour from melee combat to use this skill, which will consume all Valour to place a banner with an aura. The aura will be larger and more powerful the more Valour was consumed. The banner lasts for a duration, but will end early if you leave the aura, or use the skill again while it's active. Base duration is 10.00 seconds Base radius is 2.4 metres While you have no placed Banner, you can gain Valour 5% more Area of Effect per Valour consumed 5% more Aura effect per Valour consumed Banner grants 8% increased Movement Speed to You and Allies Banner grants +8% chance to Suppress Spell Damage to You and Allies Banner grants -5 Damage taken of each Damage Type from Suppressed Hits to You and Allies Experience: 1/49,725 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Eviscerate': `Item Class: Skill Gems Rarity: Gem Eviscerate Attack, AoE, Retaliation, Physical, Melee Level: 1 Cost: 7 Mana Cooldown Time: 3.00 sec Attack Damage: 674.5% of base Effectiveness of Added Damage: 674% Requirements: Level: 16 Str: 26 Dex: 18 Retaliate against a blocked hit with an arcing slash that releases two waves of force. Enemies close in front of you can be hit by both waves. Requires a Sword or Axe and a Shield. Cannot be used by default Becomes Usable once for 2 seconds when you Block a Hit Can't be Evaded Base wave length is 10 metres Base wave width is 2.8 metres Causes Bleeding Experience: 1/49,725 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Dread Banner': `Item Class: Skill Gems Rarity: Gem Dread Banner AoE, Spell, Duration, Aura Level: 1 Cost: 15 Mana Cooldown Time: 1.00 sec Cast Time: Instant Requirements: Level: 24 Str: 58 You must gain Valour from melee combat to use this skill, which will consume all Valour to place a banner with an aura. The aura will be larger and more powerful the more Valour was consumed. The banner lasts for a duration, but will end early if you leave the aura, or use the skill again while it's active. Base duration is 10.00 seconds Base radius is 2.4 metres While you have no placed Banner, you can gain Valour 5% more Area of Effect per Valour consumed 5% more Aura effect per Valour consumed Banner grants +4% Chance to Block Attack Damage to You and Allies Banner causes you and Allies to Recover 9 Life when Blocking Experience: 1/118,383 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Bladestorm': `Item Class: Skill Gems Rarity: Gem Bladestorm Attack, AoE, Duration, Melee Level: 1 Cost: 10 Mana Attack Speed: 70% of base Attack Damage: 159% of base Effectiveness of Added Damage: 159% Requirements: Level: 28 Str: 42 Dex: 29 Perform a spinning attack, damaging enemies around you and creating a bladestorm matching your stance. The bladestorm repeatedly damages enemies, based on your weapon damage and attack time, for a duration. Blood bladestorms are stationary and cause Bleeding, while Sand bladestorms move slowly forwards and Blind enemies. Requires a Sword or Axe. You are in Blood Stance by default. Base duration is 3.00 seconds 70% more Damage with Bleeding while in Blood Stance 10% more Attack Speed while you're in a Blood Bladestorm Maximum of 3 Bladestorms at a time Sand Bladestorms grant 30% increased Movement Speed to you Bladestorm deals 50% less Damage with Hits and Ailments Experience: 1/199,345 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Bloodlust Support': `Item Class: Support Gems Rarity: Gem Bloodlust Support Attack, Physical, Support, Melee Level: 1 Cost & Reservation Multiplier: 140% Requirements: Level: 18 Str: 33 Supports melee attack skills, causing them to deal more damage against bleeding enemies, but preventing those skills from inflicting bleeding on enemies in any way. Supported Skills deal 25% more Melee Physical Damage against Bleeding enemies Supported Attacks cannot cause Bleeding Experience: 1/69,833 This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.`,
  'Double Strike': `Item Class: Skill Gems Rarity: Gem Double Strike Attack, Melee, Strike, Physical Level: 1 Cost: 7 Mana Attack Speed: 80% of base Attack Damage: 143.8% of base Effectiveness of Added Damage: 143% Requirements: Level: 1 Performs two fast strikes with a melee weapon. 25% chance to cause Bleeding Experience: 1/70 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Puncture': `Item Class: Skill Gems Rarity: Gem Puncture Attack, Projectile, Duration, Physical, Bow Level: 1 Cost: 8 Mana Attack Speed: 70% of base Attack Damage: 168.4% of base Effectiveness of Added Damage: 168% Requirements: Level: 4 Punctures enemies with your Bow, causing a bleeding debuff, which will be affected by modifiers to skill duration. Base duration is 8.00 seconds 30% more Damage with Bleeding Causes Bleeding Experience: 1/841 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Lacerate': `Item Class: Skill Gems Rarity: Gem Lacerate Attack, AoE, Physical, Melee Level: 1 Cost: 10 Mana Attack Speed: 60% of base Attack Damage: 171.1% of base Effectiveness of Added Damage: 171% Requirements: Level: 12 Str: 14 Dex: 21 Slashes twice, releasing waves of force that damage enemies they hit. Enemies in the middle of the slashes can be hit by both. The slashes will have a chance to inflict bleeding in Blood Stance, or have a wider angle in Sand Stance. Can be used with Axes and Swords. You are in Blood Stance by default. 50% more Damage with Bleeding while in Blood Stance 25% chance to cause Bleeding while in Blood Stance 50% increased angle while in Sand Stance Experience: 1/15,249 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Toxic Rain': `Item Class: Skill Gems Rarity: Gem Toxic Rain Attack, AoE, Chaos, Duration, Projectile, Bow Level: 1 Cost: 6 Mana Attack Damage: 50% of base Effectiveness of Added Damage: 50% Requirements: Level: 12 Dex: 33 Fire arrows into the air that rain down around the targeted area, dealing damage to enemies they hit and creating spore pods where they land. Each spore pod deals chaos damage over time to nearby enemies and slows their movement speed. The pods last for a duration before bursting, dealing area damage. Deals 7.9 Base Chaos Damage per second Base duration is 1.00 seconds Fires 5 Arrows 60% of Physical Damage Converted to Chaos Damage Modifiers to Projectile Damage apply to this Skill's Damage Over Time effect Each Spore Pod applies 5% less Movement Speed to nearby Enemies, to a maximum of 30% Experience: 1/15,249 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Phase Run': `Item Class: Skill Gems Rarity: Gem Phase Run Spell, Duration, Movement, Physical, Travel Level: 1 Cost: 8 Mana Cooldown Time: 4.00 sec Cast Time: Instant Requirements: Level: 34 Dex: 79 Gain a buff that makes you faster, harder to detect, and grants Phasing, letting you pass through enemies. Performing any skill replaces this buff with one that boosts melee physical damage of skills you use yourself (it will not apply to your melee skills used by totems). Consumes Frenzy Charges to increase duration. Base duration is 1.80 seconds Base secondary duration is 0.20 seconds 20% more Melee Physical Damage 100% increased Skill Duration per Frenzy Charge removed Buff grants 30% increased Movement Speed Buff grants Phasing Buff grants 100% increased Stealth Experience: 1/252,595 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Rupture Support': `Item Class: Support Gems Rarity: Gem Rupture Support Attack, Physical, Critical, Support Level: 1 Cost & Reservation Multiplier: 140% Requirements: Level: 38 Str: 27 Dex: 39 Supports attack skills. Critical Strikes with Supported Skills that inflict Bleeding also inflict Rupture Targets take 20% more Damage from Bleeding per Rupture on them from Supported Skills Bleeding expires 25% more quickly per Rupture from Supported Skills on targets Experience: 1/388,734 This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.`,
  "Assassin's Mark": `Item Class: Skill Gems Rarity: Gem Assassin's Mark Critical, Spell, Curse, Mark Level: 1 Cost: 16 Mana Cast Time: 0.50 sec Requirements: Level: 16 Dex: 18 Int: 26 Curses a single enemy, making them more vulnerable to Critical Strikes. Killing the cursed enemy will grant life and mana, and a power charge. You can only have one Mark at a time. Cursed enemies have a 100% chance to grant a Power Charge when slain Hits against Cursed Enemies have +1.5% to Critical Strike Chance Hits against Cursed Enemies have +30% to Critical Strike Multiplier Cursed enemies grant 65 Life when Killed Cursed enemies grant 25 Mana when Killed Experience: 1/49,725 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
  'Summon Reaper': `Item Class: Skill Gems Rarity: Gem Summon Reaper Physical, Minion, Spell Level: 1 Cost: 15 Mana Cooldown Time: 4.00 sec Cast Time: 0.60 sec Requirements: Level: 28 Int: 67 Summons a powerful Reaper which uses a variety of slashing area attacks. The Reaper's presence weakens your other minions, and it will consume them to temporarily empower and heal itself. Using this skill while the Reaper is already summoned causes it to dash to the targeted location and perform a powerful attack. Maximum 1 Summoned Reaper Minion's Attacks have 50% chance to inflict Bleeding Minion deals 30% more Damage with Bleeding Reaper causes your Non-Reaper Minions to deal 20% less Damage Reaper causes your Non-Reaper Minions to have 20% less Maximum Life Experience: 1/199,345 Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.`,
};

function buildRegex(pattern: string): RegExp {
  let r = '';
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i];
    if (ch === '^' && i === 0) r += '^';
    else if (ch === '.' && pattern[i+1] === '+') { r += '.+'; i++; }
    else if (ch === '.') r += '.';
    else r += ch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(r, 'i');
}

for (const [gemName, gemText] of Object.entries(fps)) {
  const matches: string[] = [];
  for (const [patternGem, pattern] of patterns) {
    const re = buildRegex(pattern);
    if (re.test(gemText)) {
      const m = gemText.match(re);
      const idx = m?.index ?? 0;
      matches.push(`  "${pattern}" (${patternGem}) -> "${m?.[0]}" in "...${gemText.substring(Math.max(0, idx-12), idx + (m?.[0]?.length ?? 0) + 12)}..."`);
    }
  }
  if (matches.length > 0) {
    console.log(`${gemName}:`);
    for (const m of matches) console.log(m);
    console.log();
  }
}
